### ISSUE TITLE
Weird interaction with `<<type>>` and `<<capture>>` within widgets.

### ISSUE THREAD

**Issue by ChapelR** [tmedwards/sugarcube-2#177] opened 2022-07-22 03:41 UTC
**Describe the bug.**
This is a weird one, so strap in.

Consider the following widgets:
```
<<widget "works" container>><<nobr>>
  <<set _say to _contents>>
  <<capture _say>>
    <<type 50ms>><<= _say>><</type>>
  <</capture>>
<</nobr>><</widget>>

<<widget "notworking" container>><<nobr>>
  <<capture _contents>>
    <<type 50ms>><<= _contents>><</type>>
  <</capture>>
<</nobr>><</widget>>

<<widget "alsoworks" container>><<nobr>>
  <<capture _contents>>
    <<timed 50ms>><<= _contents>><</timed>>
  <</capture>>
<</nobr>><</widget>>
```

If you test all of these out, the `<<notworking>>` widget will print `[undefined]`. As near as I can tell, this only happens to widget `_args` and `_contents` special variables and only with `type`. Outside widgets or using other variables, `<<capture>>` and `<<type>>` work together as expected. Likewise, this issue does not appear to occur with other macros that delay output, as seen with the `<<alsoworks>>` widget.

**To Reproduce:**
```
:: widgets [widget]
<<widget "works" container>><<nobr>>
  <<set _say to _contents>>
  <<capture _say>>
    <<type 50ms>><<= _say>><</type>>
  <</capture>>
<</nobr>><</widget>>

<<widget "notworking" container>><<nobr>>
  <<capture _contents>>
    <<type 50ms>><<= _contents>><</type>>
  <</capture>>
<</nobr>><</widget>>

<<widget "alsoworks" container>><<nobr>>
  <<capture _contents>>
    <<timed 50ms>><<= _contents>><</timed>>
  <</capture>>
<</nobr>><</widget>>
```

```
:: Start
<<works>>Hi there yay it's me mario whee!!!!<</works>>

<<notworking>>Hi there yay it's me mario whee!!!!<</notworking>>

<<alsoworks>>Hi there yay it's me mario whee!!!!<</alsoworks>>
```

**Expected behavior.**

**Screenshots.**

**Project details.**
 - SugarCube Version: 2.36.1
 - Included Add-ons: -
 - Included Libraries: -
 - Compiler & Version: Twine 2.4.1

**Desktop details.**
 - OS & Version: [e.g., Windows 10]
 - Browser & Version [e.g., Chrome 88 (64-bit), Firefox 85 (64-bit)]

**Smartphone/tablet details.**
 - Device: [e.g., iPhone Xs Max]
 - OS & Version: [e.g., iOS 14.4]
 - Browser & Version [e.g., Safari 14.4, Firefox for iOS 31]

**Additional context.**

**Comment by tmedwards** [comment] 2022-07-22 09:32
Duplicate of #138 .

**Closed by tmedwards** 2022-07-22 09:32 UTC
Labels: bug

**Comment by ChapelR** [comment] 2022-07-22 09:40
my bad

**Comment by tmedwards** [comment] 2022-07-22 09:42
No harm, no foul.  Better a duplicate issue than not reported at all.  😄
