### ISSUE TITLE
Unused code in develop/State.prngCreate

### ISSUE THREAD

**Issue by BawdyInkSlinger** [tmedwards/sugarcube-2#282] opened 2023-11-09 03:43 UTC
**Describe the bug.**
I believe there is code in [State.prngCreate](https://github.com/tmedwards/sugarcube-2/blob/develop/src/state.js#L532C14-L535) that isn't used. I'm not sure if this is a bug or just some code that should be removed:

```js
	/*
		Returns a new PRNG wrapper object.
	*/
	function prngCreate(seed, mixEntropy) {
		const newPrng = new Math.seedrandom(seed, { // eslint-disable-line new-cap
			entropy : Boolean(mixEntropy),
			pass    : (prng, seed) => ({ prng, seed })
		});

		return Object.create(null, {
			prng : {
				value : newPrng.prng
			},
			seed : {
				value : newPrng.seed
			},
			pull : {
				writable : true,
				value    : 0
			},
			random() { // this is not a property signature
				++this.pull;
				return this.prng();
			}
		});
	}
```

I don't think `random()` does anything as written, because it doesn't have the type of a property.

**Comment by tmedwards** [comment] 2023-11-09 16:40
I'm unsure if you're having a verbiage or a knowledge breakdown, but while that is broken, it's not what you claimed.

It *is* an object literal method shorthand notation, so it's definitely a property.  The issue is that it should have been a property ***descriptor*** instead.  E.g.,

```
random : {
	value() {
		++this.pull;
		return this.prng();
	}
}
```

Regardless.  It was most certainly broken, though that wasn't the only issue with that rewritten code.  Both errors were caught because of you, so thanks.

**Comment by BawdyInkSlinger** [comment] 2023-11-09 20:23
> I'm unsure if you're having a verbiage or a knowledge breakdown, but while that is broken, it's not what you claimed.

![why-not-both-why-not](https://github.com/tmedwards/sugarcube-2/assets/51732963/6a9df7c2-cb7e-4e9a-8601-6d662b40037d)

> It _is_ an object literal method shorthand notation, so it's definitely a property. The issue is that it should have been a property _**descriptor**_ instead. 

Yep, sorry, that's what I should have said. 

> Regardless. It was most certainly broken, though that wasn't the only issue with that rewritten code. Both errors were caught because of you, so thanks.

Happy to help! Should I close this issue?

**Comment by tmedwards** [comment] 2023-11-09 23:26
You can if you want to, but there's no need.  I referenced the issue in the commit messages, so it will automatically be closed when `develop` is merged into `master`.

**Closed** 2023-11-11 23:07 UTC
Labels: bug, done
