### ISSUE TITLE
When Config.saves.autoload and Config.saves.autosave are both true, UI.restart() doesn't restart the game

### ISSUE THREAD

**Issue by hogart** [tmedwards/sugarcube-2#99] opened 2021-02-16 01:13 UTC
I'm making a game which have two language version, each in its own html file, and I wanted players to be able to switch languages on the fly without loosing progress. So I used this:
```js
Config.saves.autosave = true;
Config.saves.autoload = true;
```
But the "Restart" button in UI bar stopped working properly: it shows the prompt and refreshes the game, but game displays the same passage.

Of course I can just manually delete the responsible keys from local and session storage, and then just `Engine.restart()` but it feels wrong.

Thanks in advance for any advice!

**Comment by tmedwards** [comment] 2021-02-16 01:50
Without knowing more, I have to assume that everything is working as intended.  FYI, since this happens a lot, do not confuse the auto save with the active play session.

By setting `Config.saves.autoload` to `true` an existing auto save is automatically load upon restart.  In other words, the restart is functioning properly, the auto save is simply being loaded automatically.

You should be able to see this if you manually delete the auto save, via the Saves dialog, and then restart.

As to how to address it.  The easiest things you could do are to set `Config.saves.autoload` to:

* **`"prompt"`:** Prompts the player to load the auto save, rather than loading it automatically.
* **Function:** Allows you to determine whether the autoload happens programmatically.
* **Unset:** Allows the player to load any save at their leisure.

**Comment by hogart** [comment] 2021-02-16 01:58
The option with a function looks promising. If I use it, how do I determine if autoload happens programmatically?

**Comment by tmedwards** [comment] 2021-02-16 03:34
I'm not sure I understand the question.

As noted in [`Config.saves.autoload` docs](https://www.motoslave.net/sugarcube/2/docs/#config-api-property-saves-autoload), by setting it to a function, whether an existing auto save loads is determined by its return value: truthy to load, falsy to not.  The logic therein is your own.

I don't know how or when your language switching is running, so I can't really offer advice on how to make the two play together if that's what you're looking for.

----

As an off-hand idea.  Have you thought about not using auto loading at all, rather instead putting a continue link/button on the starting passage/screen or wherever after the language switch is done?  That should allow your switching code to work while still presenting the option to load the auto save up front to the player.

A minimal example, using macros:

```
<<if Save.autosave.has()>>
\<<link "Continue…">><<run Save.autosave.load()>><</link>>
\<</if>>
```

**Comment by hogart** [comment] 2021-02-16 03:48
Well, the "switching code" is just a `<a href="./index-en.html">EN</a>`:) Both language versions have the same story title and same passage names, so it works pretty much seamlessly.

**Comment by hogart** [comment] 2021-02-16 21:23
Turns out I don't really need autoload after all. But the "continue" link is a nice addition anyway. Thanks for the pointers!
You can close this issue.

**Comment by tmedwards** [comment] 2021-02-16 21:49
Closing.

**Closed by tmedwards** 2021-02-16 21:49 UTC
